services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_TYPE=${VPN_TYPE}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=United States
      - TZ=${TZ}
    ports:
      # - 8888:8888/tcp
      # - 8388:8388/tcp # Shadowsocks
      - 6881:6881/udp
      - 8701:8701   # qBittorrent Web UI
      - 6881:6881   # torrent port
      - 7878:7878   # Radarr
      - 8989:8989   # Sonarr
      # - 8686:8686   # Lidarr
      # - 6767:6767   # Bazarr
      - 9696:9696   # Prowlarr
      - 8191:8191   # FlareSolverr
    volumes:
      - ./appdata:/appdata
    restart: unless-stopped
    networks:
      - homelab_network
