services:  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    environment:
      - TZ=${TZ}
    depends_on:
      - gluetun
    # ports:
    #   - 8191:8191
    restart: unless-stopped